# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'simpleAddition.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class calculatorUI(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.addNums = QtWidgets.QLabel(self.centralwidget)
        self.addNums.setGeometry(QtCore.QRect(280, 50, 231, 81))
        self.addNums.setObjectName("addNums")
        self.plusSign = QtWidgets.QLabel(self.centralwidget)
        self.plusSign.setGeometry(QtCore.QRect(310, 170, 231, 81))
        self.plusSign.setObjectName("plusSign")
        self.in_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.in_1.setGeometry(QtCore.QRect(180, 200, 113, 21))
        self.in_1.setObjectName("in_1")
        self.in_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.in_2.setGeometry(QtCore.QRect(360, 200, 113, 21))
        self.in_2.setObjectName("in_2")
        self.calculate = QtWidgets.QPushButton(self.centralwidget)
        self.calculate.setGeometry(QtCore.QRect(260, 260, 113, 32))
        self.calculate.setObjectName("calculate")
        self.output = QtWidgets.QLineEdit(self.centralwidget)
        self.output.setGeometry(QtCore.QRect(520, 200, 113, 21))
        self.output.setObjectName("output")
        self.equals = QtWidgets.QLabel(self.centralwidget)
        self.equals.setGeometry(QtCore.QRect(480, 170, 231, 81))
        self.equals.setObjectName("equals")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.addNums.setText(_translate("MainWindow", "Add Two Numbers:"))
        self.plusSign.setText(_translate("MainWindow", "+"))
        self.calculate.setText(_translate("MainWindow", "Calculate"))
        self.equals.setText(_translate("MainWindow", "="))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
